spring.application.name=hello-api
management.endpoints.web.exposure.include=health,metrics,prometheus

prometheus.base-url=http://localhost:9090

management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# Use 1 minute while testing.
# Later we will change this to 5m.
traffic.window=1m
