apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: prometheus
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring

data:
  prometheus.yml: |

    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:

      # Prometheus monitors itself
      - job_name: "prometheus"

        static_configs:
          - targets:
              - "localhost:9090"


      # Monitor our traffic-test application
      - job_name: "traffic-test"

        metrics_path: /actuator/prometheus

        kubernetes_sd_configs:
          - role: pod

            namespaces:
              names:
                - default

        relabel_configs:

          # Only Running Pods
          - source_labels:
              - __meta_kubernetes_pod_phase
            action: keep
            regex: Running

          # Only traffic-test Pods
          - source_labels:
              - __meta_kubernetes_pod_label_serving_knative_dev_service
            action: keep
            regex: traffic-test

          # Only the user application's port
          - source_labels:
              - __meta_kubernetes_pod_container_port_number
            action: keep
            regex: "8080"

          # Add service name as a Prometheus label
          - source_labels:
              - __meta_kubernetes_pod_label_serving_knative_dev_service
            target_label: service_name

          # Also save Pod name as a label
          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
      
      # Monitor traffic-test when it is an HPA application
      - job_name: "traffic-test-hpa"

        metrics_path: /actuator/prometheus

        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - default

        relabel_configs:

          # Only Running Pods
          - source_labels:
              - __meta_kubernetes_pod_phase
            action: keep
            regex: Running

          # HPA Deployment Pods use app=<service-name>
          - source_labels:
              - __meta_kubernetes_pod_label_app
            action: keep
            regex: traffic-test

          # Only Spring Boot port
          - source_labels:
              - __meta_kubernetes_pod_container_port_number
            action: keep
            regex: "8080"

          # Store application name as service_name
          - source_labels:
              - __meta_kubernetes_pod_label_app
            target_label: service_name

          # Store Pod name
          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring

spec:
  replicas: 1

  selector:
    matchLabels:
      app: prometheus

  template:
    metadata:
      labels:
        app: prometheus

    spec:
      serviceAccountName: prometheus

      containers:
        - name: prometheus

          image: prom/prometheus:v3.13.2

          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention.time=6h"

          ports:
            - containerPort: 9090

          volumeMounts:
            - name: config
              mountPath: /etc/prometheus

            - name: data
              mountPath: /prometheus

      volumes:

        - name: config
          configMap:
            name: prometheus-config

        - name: data
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring

spec:
  selector:
    app: prometheus

  ports:
    - port: 9090
      targetPort: 9090

  type: ClusterIP